---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springcloudservices/spring-cloud-base

inputs:
- name: src
- name: src-ci

run:
  path: src-ci/ci/tasks/push/push.sh