---
resources:
- name: src
  type: git
  source:
    uri: {{github-uri}}
    branch: master

jobs:
- name: push-to-cf
  serial_groups: [master-deployment]
  plan:
  - get: src
    trigger: true
  - task: push-pull-request
    file: src/ci/tasks/push/push.yml
    input_mapping:
      src: src
    params:
      APP_NAME: mendix-demo-app
      DB_NAME: mendix-demo-db
      DB_SERVICE_NAME: cleardb
      DB_SERVICE_PLAN: spark
      CF_API: {{cf-api}}
      CF_USER: {{cf-user}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-prod-org}}
      CF_SPACE: {{cf-prod-space}}}
      APP_HOSTNAME: {{app-hostname}}
      APP_DOMAIN: {{app-domain}}
      ENVIRONMENT: master

- name: run-smoke-tests
  serial_groups: [master-deployment]
  plan:
  - get: src
    passed: [push-to-cf]
    trigger: true
  - task: run-smoke-tests
    file: src/ci/tasks/smoke-tests/smoke-tests.yml
    input_mapping:
      src: src
    params:
      URL: {{app-url}}