---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: src-pr
  type: pull-request
  source:
    repo: daniellavoie/pcf-mendix-demo
    access_token: {{github-access-token}}
    uri: {{github-uri}}

jobs:
- name: push-to-cf
  serial_groups: [pull-request-deployment]
  plan:
  - get: src-pr
    trigger: true
  - put: src-pr
    params:
      path: src-pr
      status: pending
  - task: push-pull-request
    file: src-pr/ci/tasks/push/push.yml
    input_mapping:
      src: src-pr
    params:
      APP_NAME: mendix-demo-app
      DB_NAME: mendix-demo-db
      DB_SERVICE_NAME: cleardb
      DB_SERVICE_PLAN: spark
      CF_API: {{cf-api}}
      CF_USER: {{cf-user}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-org}}
      CF_SPACE: {{cf-space}}
      ENVIRONMENT: pull-request
      APP_HOSTNAME: {{app-hostname}}
      APP_DOMAIN: {{app-domain}}
      on_failure:
        put: src-pr
        params:
          path: src-pr
          status: failure

- name: run-smoke-tests
  serial_groups: [pull-request-deployment]
  plan:
  - get: src-pr
    passed: [push-to-cf]
    trigger: true
  - task: run-smoke-tests
    file: src-pr/ci/tasks/smoke-tests/smoke-tests.yml
    input_mapping:
      src: src-pr
    params:
      URL: {{app-url}}
    on_failure:
      put: src-pr
      params:
        path: src-pr
        status: failure
    on_success:
      put: src-pr
      params:
        path: src-pr
        status: success