---
resources:
- name: src
  type: git
  source:
    branch: master
    uri: {{github-uri}}
- name: version
  type: semver
  source:
    branch: version
    driver: git
    file: version
    initial_version: 0.1.0
    uri: {{github-uri}}

jobs:
- name: deploy-to-master-release-train
  serial_groups:
  - master-deployment
  plan:
  - get: src
    trigger: true
  - task: push-pull-request
    file: src/ci/tasks/push/push.yml
    params:
      APP_NAME: mendix-demo-app
      CF_API: {{cf-api}}
      CF_ORG: {{cf-release-train-org}}
      CF_PASSWORD: {{cf-password}}
      CF_SPACE: {{cf-release-train-space}}
      CF_USER: {{cf-user}}
      DB_NAME: mendix-demo-db
      DB_SERVICE_NAME: cleardb
      DB_SERVICE_PLAN: spark
      ENVIRONMENT: master-release-train
      APP_HOSTNAME: {{app-release-train-hostname}}
      APP_DOMAIN: {{app-release-train-domain}}
    input_mapping:
      src: src

- name: run-smoke-tests-master
  serial_groups:
  - master-deployment
  plan:
  - get: version
  - get: src
    passed:
    - deploy-to-master-release-train
    trigger: true
  - task: run-smoke-tests
    file: src/ci/tasks/smoke-tests/smoke-tests.yml
    input_mapping:
      src: src
    params:
      URL: {{app-release-train-url}}
  - put: version
    params:
      file: version/version

- name: deploy-to-production
  serial_groups:
  - blue-green-deployment
  plan:
  - get: src
    passed:
    - run-smoke-tests-master
  - get: version
    passed:
    - run-smoke-tests-master
  - task: blue-green-deploy
    file: src/ci/tasks/blue-green-deploy/blue-green-deploy.yml
    params:
      CF_API: {{cf-api}}
      CF_USER: {{cf-user}}
      CF_PASSWORD: {{cf-password}}
      APP_NAME: mendix-demo-app
      CF_ORG: {{cf-prod-org}}
      CF_SPACE: {{cf-prod-space}}
      ENVIRONMENT: production
      APP_HOSTNAME: {{app-prod-hostname}}
      APP_DOMAIN: {{app-prod-domain}}
    input_mapping:
      src: src

- name: run-smoke-tests-production
  serial_groups:
  - blue-green-deployment
  plan:
  - get: src
    passed:
    - deploy-to-production
    trigger: true
  - get: version
    passed:
    - run-smoke-tests-master
  - task: run-smoke-tests
    file: src/ci/tasks/smoke-tests/smoke-tests.yml
    input_mapping:
      src: src
    params:
      URL: {{app-prod-url}}